title: Linkblog
subtitle: 'API Documentation'
description: A personal bookmarking API that publishes an RSS feed
url: https://www.linkblog.in
baseurl: ''

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-include-cache

breadcrumbs: true
